title: Coy's Page
author: Coy McNew
email: mcnewcp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a space where I (Coy McNew) am just trying out
  github pages to see if it's something I am interested in
  and capable of establishing and maintaining. 

theme: minima

# social links
twitter_username: mcnewcp # DO NOT include the @ character, or else the build will fail!
github_username:  mcnewcp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
